server:
  port: 9999
  contextPath: /auth

org:
  springframework:
    boot:
      autoconfigure:
        security: INFO

management:
  security:
    enabled: false

---
# For deployment in Docker containers
spring:
  profiles: docker

server:
  port: 9999

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
